- hosts: all

  vars:
    pip_pkg: Flask

  tasks:
    - name: Get latest version of pip package
      shell: "curl -s https://pypi.org/pypi/{{ pip_pkg }}/json | jq --raw-output '.info.version'"
      register: pip_package_latest_version

    - name: Create template of requirements.txt
      template:
        src: requirements.txt.j2
        dest: requirements.txt
