- hosts: localhost
  gather_facts: no

  tasks:
    - name: Get latest version of pip package
      uri:
        url: "https://pypi.org/pypi/Flask/json"
        method: GET
        status_code: 200
        body_format: json
      register: pypi_Flask

    - set_fact:
        flask_latest: pypi_Flask.json.info.version

    - name: Create template of requirements.txt
      template:
        src: requirements.txt.j2
        dest: requirements.txt
